import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Francis",
  description: "Generated by Francisco",
  keywords: ["About", "Francis Works"],
};

export default function AboutPage() {
  return (
    <>
      <h1>About</h1>
    </>
  );
}
