import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Francis",
    description: "Generated by Francisco",
    keywords: ["Icon", "Francis Works"],
  };

export default function IconoPage() {
  return (
    <>
      <h1>icono</h1>
    </>
  );
}
