import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Francis",
  description: "Generated by Francisco",
  keywords: ["Main", "Francis"],
};

export default function Main() {
  return (
    <div>
      <h1>Hello Page</h1>
    </div>
  );
}
