
 import CartCounter from "@/app/shopping-cart/components/CartCounter";
import { Metadata } from "next"; 






 export const metadata: Metadata = {
  title: "Francis",
  description: "Generated by Francisco",
  keywords: ["Counter", "Francis"],
}; 

export default function Counter() {
  return (
    <div className="flex flex-col items-center justify-center w-full h-full">
      <span className="text-3xl font-bold underline">
        Productos en el carrito
      </span>
      <CartCounter value={0} />
    </div>
  );
}
