import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Francis",
    description: "Generated by Francisco",
    keywords: ["Contact", "Francis Works"],
  };

export default function ContactPage() {
  return (
    <>
      <h1>contact</h1>
    </>
  );
}
